<?php
/**
 * Created by PhpStorm.
 * User: mjz
 * Date: 17/10/21
 * Time: 下午3:03
 */

namespace backend\models;


use common\models\records\ConsumeLog;
use yii\base\Model;

class MangageHuobiForm extends Model
{
    public $user_id;
    public $huobi_type;
    public $count;

    public function rules()
    {
        return [
            [['user_id', 'huobi_type', 'count'], 'integer'],
            [['user_id', 'huobi_type', 'count'], 'required'],
            ['huobi_type', 'in', 'range' => [ConsumeLog::CURRENCY_HUOBI, ConsumeLog::CURRENCY_DIANZIBI]]
        ];
    }

    public function attributeLabels()
    {
        return [
            'user_id' => '用户',
            'huobi_type' => '钱币类型',
            'count' => '数值'
        ]; // TODO: Change the autogenerated stub
    }

    public function save() {
        $model = new ConsumeLog();

        return true;
    }
}