<?php
/**
 * Created by PhpStorm.
 * User: mjz
 * Date: 17/10/26
 * Time: 上午12:07
 */

namespace common\core;


use yii\grid\DataColumn;

class DefaultDataColumn extends DataColumn
{
    public $defaultValue;

    public function getDataCellValue($model, $key, $index)
    {
        $value = parent::getDataCellValue($model, $key, $index); // TODO: Change the autogenerated stub
        if ($value === null) {
            return $this->defaultValue;
        }
        return $value;
    }
}